version: '3.8'

services:
  # PostgreSQL 16 service
  postgres:
    image: postgres:16
    hostname: postgres
    env_file:
      - .postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql
    ports:
      - "5432:5432"
    networks:
      - hrstrat-network

  # Spring Boot backend service
  backend:
    image: 764615761561.dkr.ecr.us-east-1.amazonaws.com/ebs-hrstrat/backend:latest
    hostname: backend
    depends_on:
      - postgres
    env_file:
      - .backend.env
    networks:
      - hrstrat-network

  # Angular frontend service
  frontend:
    image: 764615761561.dkr.ecr.us-east-1.amazonaws.com/ebs-hrstrat/frontend:latest
    hostname: frontend
    depends_on:
      - backend
    networks:
      - hrstrat-network

  # Nginx reverse proxy service
  nginx-proxy:
    image: docker.io/jc21/nginx-proxy-manager:latest
    hostname: nginx-proxy
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - hrstrat-network

networks:
  hrstrat-network:
    driver: overlay

volumes:
  postgres_data:
